# Generated by Django 4.1.7 on 2023-03-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('calories', models.PositiveSmallIntegerField()),
                ('fat', models.PositiveSmallIntegerField()),
                ('carbs', models.PositiveSmallIntegerField()),
                ('protein', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_meal', models.IntegerField(choices=[(0, 'breakfast & brunch'), (1, 'lunch'), (2, 'dinner'), (3, 'appetizers & snacks'), (4, 'cocktails')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
                ('total_time', models.PositiveIntegerField()),
                ('servings', models.PositiveSmallIntegerField()),
                ('ingredients', models.ManyToManyField(to='Dish_Helper_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dish_Helper_app.ingredient')),
            ],
        ),
    ]
