# Generated by Django 4.1.7 on 2023-03-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dish_Helper_app', '0002_profile_delete_user_remove_meal_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_name',
        ),
    ]
