# Generated by Django 4.1.7 on 2023-04-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dish_Helper_app', '0008_alter_ingredientmeasurement_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofmeal',
            old_name='type',
            new_name='meal',
        ),
    ]
