# Generated by Django 4.1.7 on 2023-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish_Helper_app', '0010_alter_ingredient_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
