# Generated by Django 4.1.7 on 2023-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish_Helper_app', '0011_alter_ingredient_carbs_alter_ingredient_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='servings',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
